/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSurfaceCard: typeof import('./components/AppSurfaceCard.vue')['default']
    CloseConfirmDialog: typeof import('./components/CloseConfirmDialog.vue')['default']
    CurrentSource: typeof import('./components/CurrentSource.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ProxySettings: typeof import('./components/ProxySettings.vue')['default']
    RegistryDialog: typeof import('./components/RegistryList/RegistryDialog.vue')['default']
    RegistryList: typeof import('./components/RegistryList/index.vue')['default']
    SettingsDrawer: typeof import('./components/SettingsDrawer.vue')['default']
    SpeedTest: typeof import('./components/SpeedTest.vue')['default']
  }
}
